### ISSUE TITLE
Error: Server at 127.0.0.1:11211 not available

### ISSUE THREAD

**Issue by holoduke** [3rd-Eden/node-memcached#229]
I am running a website with 10k + concurrent connections.
since i updated node memcached with npm today on a debian machine, i am receiving 
Error: Server at 127.0.0.1:11211 not available for almost 75% of all calls.
I have no clue what it might be. I also had max value size errors, but those i have secured by setting the maxvalue setting.
I tried to increase the poolsize to 999999, but it did not help.
any ideas??

**Comment by holoduke** [comment]
Ok my mistake. the size of values cached in memcache was increased to 500kb for every put.
mistake from another program. 
this one can be closed

**Comment by 4h0y** [comment]
@holoduke Hello.

I just had the same problem. Memcached did not update, did not touch anything, everything worked fine until now.

Can you tell us more in detail, because of what was the error?

```
# service memcached status
● memcached.service - memcached daemon
   Loaded: loaded (/lib/systemd/system/memcached.service; disabled)
   Active: active (running) since Thu 2017-03-23 08:35:35 EDT; 10s ago
 Main PID: 1538 (memcached)
   CGroup: /system.slice/memcached.service
           └─1538 /usr/bin/memcached -m 64 -p 11211 -u memcache -l 127.0.0.1

Mar 23 08:35:35 trampamp systemd[1]: Starting memcached daemon...
Mar 23 08:35:35 trampamp systemd[1]: Started memcached daemon.
```

LOG
```
Error: Server at 127.0.0.1:11211 not available
at Client.memcachedCommand [as command] (/home/hello.com/node_modules/memcached/lib/memcached.js:306:70)
at Client.get (/home/hello.com/node_modules/memcached/lib/memcached.js:830:10)

```

```
# telnet 127.0.0.1 11211
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
stats
STAT pid 1538
STAT uptime 876
STAT time 1490273409
STAT version 1.4.21
STAT libevent 2.0.21-stable
STAT pointer_size 64
STAT rusage_user 0.025996
STAT rusage_system 0.006998
STAT curr_connections 5
STAT total_connections 8
STAT connection_structures 6
STAT reserved_fds 20
STAT cmd_get 0
STAT cmd_set 0
STAT cmd_flush 2
STAT cmd_touch 0
STAT get_hits 0
STAT get_misses 0
STAT delete_misses 0
STAT delete_hits 0
STAT incr_misses 0
STAT incr_hits 0
STAT decr_misses 0
STAT decr_hits 0
STAT cas_misses 0
STAT cas_hits 0
STAT cas_badval 0
STAT touch_hits 0
STAT touch_misses 0
STAT auth_cmds 0
STAT auth_errors 0
STAT bytes_read 46
STAT bytes_written 15
STAT limit_maxbytes 67108864
STAT accepting_conns 1
STAT listen_disabled_num 0
STAT threads 4
STAT conn_yields 0
STAT hash_power_level 16
STAT hash_bytes 524288
STAT hash_is_expanding 0
STAT malloc_fails 0
STAT bytes 0
STAT curr_items 0
STAT total_items 0
STAT expired_unfetched 0
STAT evicted_unfetched 0
STAT evictions 0
STAT reclaimed 0
STAT crawler_reclaimed 0
STAT lrutail_reflocked 0
END
```

**Comment by Zorono** [comment]
any updates on this ??!
