### ISSUE TITLE
I use node.js 0.12 or iojs has error message.

### ISSUE THREAD

**Issue by goalsoft** [3rd-Eden/node-memcached#238]
/usr/lib/node_modules/memcached/node_modules/hashring/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Module.require (module.js:349:17)
    at require (module.js:368:17)
    at bindings (/usr/lib/node_modules/memcached/node_modules/hashring/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/lib/node_modules/memcached/node_modules/hashring/index.js:3:36)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)

**Comment by 3rd-Eden** [comment]
.looks me that you also globally installed the node modules as it's in `/usr/lib/node_modules`. The Module did not self-register is usually an indication that you did not install the node modules after switching node.js or iojs versions. Binary modules always need to be rebuild when you switch versions. If a re-install doesn't solve it try to install the master branch of this repository using `npm install 3rd-Eden/node-memcached`

**Comment by meteormatt** [comment]
I also face this problem
```
d:\workspace_git\gokuai-notify\node_modules\memcached\node_modules\hashring\node_modules\bindings\bindings.js:91
  throw err
        ^
Error: Could not locate the bindings file. Tried:
 → d:\workspace_git\gokuai-notify\node_modules\memcached\node_modules\hashring\build\hashvalue.node
 → d:\workspace_git\gokuai-notify\node_modules\memcached\node_modules\hashring\build\Debug\hashvalue.node
 → d:\workspace_git\gokuai-notify\node_modules\memcached\node_modules\hashring\build\Release\hashvalue.node
 → d:\workspace_git\gokuai-notify\node_modules\memcached\node_modules\hashring\out\Debug\hashvalue.node
 → d:\workspace_git\gokuai-notify\node_modules\memcached\node_modules\hashring\Debug\hashvalue.node
 → d:\workspace_git\gokuai-notify\node_modules\memcached\node_modules\hashring\out\Release\hashvalue.node
 → d:\workspace_git\gokuai-notify\node_modules\memcached\node_modules\hashring\Release\hashvalue.node
 → d:\workspace_git\gokuai-notify\node_modules\memcached\node_modules\hashring\build\default\hashvalue.node
 → d:\workspace_git\gokuai-notify\node_modules\memcached\node_modules\hashring\compiled\0.12.1\win32\ia32\hashvalue.node
    at bindings (d:\workspace_git\gokuai-notify\node_modules\memcached\node_modules\hashring\node_modules\bindings\bindings.js:88:9)
    at Object.<anonymous> (d:\workspace_git\gokuai-notify\node_modules\memcached\node_modules\hashring\index.js:3:36)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (d:\workspace_git\gokuai-notify\node_modules\memcached\lib\memcached.js:12:16)
    at Module._compile (module.js:460:26)
```
